SELECT AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, sum(A.sales*BOOK.PRICE) AS SALES
FROM BOOK
JOIN(
    SELECT book_id, sum(sales) as sales
    FROM BOOK_SALES
    WHERE sales_date BETWEEN "2022-01-01" and "2022-01-31"
    GROUP BY book_id) A
ON BOOK.BOOK_ID = A.BOOK_ID
JOIN AUTHOR
ON BOOK.AUTHOR_ID=AUTHOR.AUTHOR_ID
GROUP BY AUTHOR.AUTHOR_NAME, BOOK.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC



    # SELECT book_id, sum(sales) as sales
    # FROM BOOK_SALES
    # WHERE sales_date BETWEEN "2022-01-01" and "2022-01-31"
    # GROUP BY book_id
    # SELECT * FROM BOOK
    
    