-- 코드를 입력하세요

SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.ANIMAL_TYPE, ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS
JOIN(
    SELECT * FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE "Intact%"
    ) A
ON A.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_OUTS.SEX_UPON_OUTCOME LIKE "Spayed%" OR  ANIMAL_OUTS.SEX_UPON_OUTCOME LIKE "Neutered%"
ORDER BY ANIMAL_OUTS.ANIMAL_ID