-- 코드를 입력하세요
# SELECT *#, SUM(TOTAL_ORDER)
# FROM FIRST_HALF
# GROUP BY FLAVOR

SELECT FLAVOR 
FROM (
    SELECT JULY.FLAVOR , SHIPMENT_ID, SUM(TOTAL_ORDER)+F.TOTAL AS TOTAL_ORDER
    FROM JULY
    JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
        FROM FIRST_HALF
        GROUP BY FLAVOR ) AS F
    ON JULY.FLAVOR = F.FLAVOR
    GROUP BY FLAVOR
    ORDER BY TOTAL_ORDER DESC
    LIMIT 3
) AS A

    # SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    # FROM FIRST_HALF
    # GROUP BY FLAVOR
    
    # SELECT * FROM FIRST_HALF #GROUP BY FLAVOR