# SELECT MEMBER_ID, COUNT(MEMBER_ID) as cnt
# FROM REST_REVIEW
# GROUP BY MEMBER_ID
# ORDER BY cnt DESC
# LIMIT 3

# SELECT * FROM MEMBER_PROFILE

# SELECT MEMBER_ID, COUNT(MEMBER_ID) as cnt
# FROM REST_REVIEW
# GROUP BY MEMBER_ID
# ORDER BY cnt DESC
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MP
JOIN REST_REVIEW RR
  ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE RR.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;
