SELECT CATEGORY, FOOD_PRODUCT.PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT  
JOIN (
    SELECT MAX(PRICE) as PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    ORDER BY CATEGORY,PRICE) A
ON FOOD_PRODUCT.PRICE = A.PRICE
WHERE CATEGORY IN ('국','식용유','김치','과자')
GROUP BY CATEGORY
ORDER BY PRICE DESC


# P0093	맛있는허니버터칩	CD_CK00003	과자	1950